version: '3.8'

services:
  application-service:
    build:
      context: ./application-service
    depends_on:
      - cassandra-db
    env_file:
      - .env
    ports:
      - "8084:8080"

  assessment-service:
    build:
      context: ./assessment-service
    depends_on:
      - cassandra-db
    env_file:
      - .env
    ports:
      - "8083:8080"

  career-program-service:
    build:
      context: ./career-program-service
    depends_on:
      - cassandra-db
    env_file:
      - .env
    ports:
      - "8082:8080"

  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - kafka
    ports:
      - "8085:8080"

  user-management-service:
    build:
      context: ./user-management-service
    depends_on:
      - postgresql
    env_file:
      - .env
    ports:
      - "8081:8080"

  cassandra-db:
    image: cassandra:latest
    ports:
      - "9042:9042"  # Cassandra default port
    volumes:
      - cassandra-data:/var/lib/cassandra

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skillspace_users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  cassandra-data:
  postgres-data: