server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
        - id: career-service
          uri: lb://career-program-service
          predicates:
            - Path=/careers/**
        - id: assessment-service
          uri: lb://assessment-service
          predicates:
            - Path=/assessments/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
