server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
      routes:
        # user-service
        - id: user-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
        - id: user-service-admin
          uri: lb://user-management-service
          predicates:
            - Path=/admin/**
        - id: user-service-talent
          uri: lb://user-management-service
          predicates:
            - Path=/talent/**
          filters:
            - JwtAuthenticationFilter
        - id: user-service-company
          uri: lb://user-management-service
          predicates:
            - Path=/company/**
          filters:
            - JwtAuthenticationFilter
        - id: user-service-accounts
          uri: lb://user-management-service
          predicates:
            - Path=/api/account/**
        - id: user-service-auth
          uri: lb://user-management-service
          predicates:
            - Path=/auth/**, /api/password-reset/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: user-service-api-docs
          uri: lb://user-management-service
          predicates:
            - Path=/users/v3/api-docs, /users/swagger-ui.html
          filters:
            - StripPrefix=1

        # career-service
        - id: career-service
          uri: lb://career-program-service
          predicates:
            - Path=/careers/**
          filters:
            - JwtAuthenticationFilter
        - id: career-service-api-docs
          uri: lb://career-program-service
          predicates:
            - Path=/careers/v3/api-docs, /careers/swagger-ui.html
          filters:
            - StripPrefix=1

        # assessment-service
        - id: assessment-service
          uri: lb://assessment-service
          predicates:
            - Path=/assessments/**
          filters:
            - JwtAuthenticationFilter
        - id: assessment-service-api-docs
          uri: lb://assessment-service
          predicates:
            - Path=/assessments/v3/api-docs, /assessments/swagger-ui.html
          filters:
            - StripPrefix=1

        # application-service
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/applications/**
          filters:
            - JwtAuthenticationFilter
        - id: application-service-api-docs
          uri: lb://application-service
          predicates:
            - Path=/applications/v3/api-docs, /applications/swagger-ui.html
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /users/v3/api-docs
        name: User Service API
      - url: /careers/v3/api-docs
        name: Career Service API
      - url: /assessments/v3/api-docs
        name: Assessment Service API
      - url: /applications/v3/api-docs
        name: Application Service API

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    com.skillspace.gateway: DEBUG